comfyui:
  api_url: http://127.0.0.1:8989
  reference_image_mode: true
default_workflow:
  name: nunchaku-flux.1-dev.json
llm:
  api_key: AIzaSyBatnvA5p5hgRyCoa4AF_7YjrHdz227dR8
  api_url: https://generativelanguage.googleapis.com
  model_name: gemini-2.0-flash
  proxies: null
  verify_ssl: false
  window_size: 4
  parse_retries: 2
relative_projects_path: ../projects/
relative_prompts_path: prompts/
relative_workflow_path: workflow/
