comfyui:
  api_url: http://localhost:8188
default_workflow:
  name: comfyui.json
llm:
  api_key: YOUR_API_KEY_HERE
  api_url: https://api.example.com/v1
  model_name: your-model-name
  proxies: null
  verify_ssl: false
  window_size: 3
projects_path: ../projects/
prompts_path: prompts/ 