comfyui:
  api_url: http://127.0.0.1:8000
default_workflow:
  name: nunchaku-flux.1-dev.json
llm:
  api_key: sk-jbmoetlepdnlssacqpvunssgsxyduuoihgymxvkfhwohtauc
  api_url: https://api.siliconflow.cn/v1
  model_name: deepseek-ai/DeepSeek-V3
  proxies: null
  verify_ssl: false
  window_size: 4
relative_projects_path: ../projects/
relative_prompts_path: prompts/
relative_workflow_path: workflow/
