comfyui:
  api_url: http://192.168.10.9:8188
default_workflow:
  name: comfyui.json
llm:
  api_key: your-key
  api_url: https://api.siliconflow.cn/v1
  model_name: deepseek-ai/DeepSeek-V2.5
  proxies: null
  verify_ssl: false
  window_size: 3  # 文本分割的窗口大小，-1表示不分割
projects_path: ../projects/
prompts_path: prompts/
